name: sensorlab
description: "Measure ambient light, detect sound levels, and sense nearby objects using your phoneâ€™s built-in sensors. This app provides a simple and intuitive interface for accessing and visualizing sensor data, making it easy to monitor your environment and gather information about the world around you."
publish_to: "none"
version: 1.1.1+8

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- State Management ---
  flutter_riverpod: ^2.3.6

  # --- Permissions & System Services ---
  permission_handler: ^11.4.0
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  pedometer: ^4.1.1
  vibration: ^3.1.3
  torch_light: ^1.1.0

  # --- Sensors ---
  light: ^4.1.0
  sensors_plus: ^6.1.1
  proximity_sensor: ^1.3.8
  noise_meter: ^5.0.1
  flutter_compass: ^0.8.1
  mobile_scanner: ^6.0.7
  camera: ^0.11.1

  # --- Database & Storage ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.3
  path_provider: ^2.1.2

  # --- Network & API ---
  http: ^1.2.2
  flutter_dotenv: ^6.0.0

  # --- UI & Visualization ---
  fl_chart: ^0.70.2
  font_awesome_flutter: ^10.8.0
  iconsax: ^0.0.8
  liquid_pull_to_refresh: ^3.0.1
  google_mobile_ads: ^5.3.1
  url_launcher: ^6.3.1
  go_router: ^14.6.1

  # --- Localization & Utils ---
  flutter_localization: ^0.3.3
  logger: ^2.6.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # --- Code Generation ---
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/compass.png
    - assets/icons/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#0B3F69"
    theme_color: "#0B3F69"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"
